### ISSUE TITLE
インクリメント演算子の結果がおかしい

### ISSUE THREAD

**Issue by doly** [wakamori/Veins#8]
Aspen 上のインクリメント演算子の
計算結果がおかしいです。

int i = 0;
i++;
System.out.println(i);
結果
0

となってインクリメントがなされていません。

i = i+1; は、正しく計算されています。

int i = 0;
i = i+1;
System.out.println(i);

結果
1

for 文や、while 文の中では、インクリメント演算子は
正しく動作しているようです。

for (int j=1; j<=3; j++) {
  System.out.println(j);
}
結果
1
2
3

int k = 0;
while (k <= 2) {
  k++;
  System.out.println(k);
}

結果
1
2
3

**Comment by wakamori** [comment]
修正しました．

**Comment by doly** [comment]
修正されていることを確認しました。
